[package]
name = "fast_desmos2_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.6.0"
color-eyre = "0.6.3"
self_cell = "1.0.4"
thiserror = "2.0.3"
winnow = "0.6.20"
fast_desmos2_utils = { path="../fast_desmos2_utils" }
