#version 430

layout(local_size_x = 128) in;

layout(std430, binding = 0) buffer instanceLayout
{
    vec2 inst_points[];
};

float hashfloat(vec2 p) {
  float hash = mod(p.x, 289.0);
  hash = mod((hash*51.0 + 2.0)*hash + p.y, 289.0);
  hash = mod((hash*34.0 + 10.0)*hash, 289.0);
  return hash;
}

uint hash32(uint x)
{
    x ^= x >> 16;
    x *= 0x7feb352dU;
    x ^= x >> 15;
    x *= 0x846ca68bU;
    x ^= x >> 16;
    return x;
}

void main() {
    uint global_index = gl_GlobalInvocationID.x * 2;

    uint hash_x = hash32(global_index);
    uint hash_y = hash32(global_index + 1);

    inst_points[global_index] = vec2(
        float(hash_x) / 4294967296.0,
        float(hash_y) / 4294967296.0
    );
}
