#version 430

layout(local_size_x = 128) in;

layout(std430, binding = 0) buffer instanceLayout
{
    vec2 inst_points[];
};

layout(std430, binding = 1) buffer instanceLayoutNew
{
    vec2 new_inst_points[];
};

layout(location=0) uniform float dt;

vec2 acceleration(vec2 pos, vec2 vel) {
    ivec2 corner = ivec2(floor(pos)) % 2;
    int idx = corner.x + corner.y * 2;

    vec2 v = vec2(0);
    switch (idx) {
        case 0:
            v = vec2(-1.0, 0.0);
            break;
        case 1:
            v = vec2( 0.0, 1.0);
            break;
        case 3:
            v = vec2( 1.0, 0.0);
            break;
        case 2:
            v = vec2( 0.0,-1.0);
            break;
    };
    return v;
}

void main() {
    uint global_index = gl_GlobalInvocationID.x * 2;

    vec2 pos = inst_points[global_index];
    vec2 vel = inst_points[global_index + 1];

    vec2 new_vel = vel + acceleration(pos, vel) * dt;
    vec2 new_pos = pos + vel * dt;

    new_inst_points[global_index] = new_pos;
    new_inst_points[global_index + 1] = new_vel;
}
