[package]
name = "fast_desmos2_tree_parser"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fast_desmos2_tree_parser"
required-features = ["binary"]

[features]
binary = ["dep:pretty_assertions"]

[dependencies]
color-eyre = "0.6.3"
fast_desmos2_tree = { path = "../fast_desmos2_tree" }
fast_desmos2_utils = { path = "../fast_desmos2_utils" }
fast_desmos2_eval = { path = "../fast_desmos2_eval" }
winnow = "0.6.20"
pretty_assertions = { version = "1.4.1", optional = true }

[dev-dependencies]
pretty_assertions = "1.4.1"
